sudo: false
language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
env:
  matrix:
    - RAILS_VERSION='~> 4.2.0'
    - RAILS_VERSION='~> 5.0.0'
    - RAILS_VERSION='~> 5.1.x'
before_install: gem install bundler -v 1.14.6
